from typing import Protocol
from pathlib import Path
from wiki.models.wiki_page import WikiPage

class IWikiRepository(Protocol):
    def get_by_name(self, name: str) -> WikiPage | None: ...
    def list_all(self) -> list[WikiPage]: ...
    def read(self, page: WikiPage) -> str: ...

class IPdfRenderer(Protocol):
    def render(self, html_file: Path, pdf_file: Path) -> Path: ...