name: Python Package Wiki

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    name: Dev Test
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Instalar o Poetry
        run: pipx install poetry

      - name: Configurar o Python e o Cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Instalar Dependências
        run: poetry install --no-interaction

      - name: Rodar Testes e Gerar Relatório de Cobertura
        run: poetry run pytest --cov=src/wiki tests/

      - name: Build Package
        run: poetry build